#!/bin/bash

export HOME="/var/lib/irods"
HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"
#INTERVAL="${COLLECTD_INTERVAL:-60}"
INTERVAL=60

while sleep "$INTERVAL"; do
    # total number of users
    users=$(ils /ebrc/workspaces/users | grep -c '  C- ')
    echo "PUTVAL \"$HOSTNAME/workspaces/gauge-users\" interval=$INTERVAL N:$users"
    # total number of events
    events=$(iquest --no-page "select DATA_NAME where COLL_NAME like '/ebrc/workspaces/events'"|grep -c ^DATA_NAME)
    echo "PUTVAL \"$HOSTNAME/workspaces/gauge-events\" interval=$INTERVAL N:$events"
    # total number of datasets
    datasets=$(iquest --no-page "select COLL_NAME where COLL_NAME like '/ebrc/workspaces/users/%/datasets/%' and COLL_NAME not like '%datafiles' and  COLL_NAME not like '%sharedWith'"| grep -c ^COLL_NAME)
    echo "PUTVAL \"$HOSTNAME/workspaces/gauge-datasets\" interval=$INTERVAL N:$datasets"

done
